{
    "name": "Gestión de Puertos y Zonas de carga",
    "version": "1.0.0",
    "summary": "Módulo para la gestión de puertos y zonas de carga",
    "description": "-.-",
    "author": "Jhonny",
    "website": "https://github.com/vandalieu06",
    "depends": ["base", "fleet", "web", "website"],
    "data": [
        "security/ir.model.access.csv",
        "views/view_fleet_port.xml",
        "views/code_port_increment.xml",
        "views/portal_templates.xml",
        # Dashboard and charts
        "views/dashboard_views.xml",
        "views/dashboard_templates.xml",
        "views/chart_templates.xml",
        "data/cron_jobs.xml",
    ],
    "images": ["static/description/icon.png"],
    "license": "AGPL-3",
    "category": "Website/Services",
    "application": True,
    "installable": True,
}
